version: '3'

services:

  frontend:
    image: front-app

  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  alineaciones-partido:
    image: python
    volumes:
        - ./python/alineaciones_partido.py:/app/alineaciones_partido.py
    command: [python, -u,"/app/alineaciones_partido.py"]

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # Mapea el puerto 5672 del contenedor al puerto 5672 del host

  producer:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq-producer/Dockerfile
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq-consumer/Dockerfile
    depends_on:
      - rabbitmq
