version: '3'

services:

  frontend:
    image: front-app

  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  alineaciones-partido:
    image: python
    volumes:
        - ./python/alineaciones_partido.py:/app/alineaciones_partido.py
    command: [python, -u,"/app/alineaciones_partido.py"]

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # Mapea el puerto 5672 del contenedor al puerto 5672 del host

  producer:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq-producer/Dockerfile
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq-consumer/Dockerfile
    depends_on:
      - rabbitmq
  api_descarga:
    image: openjdk
    volumes:
      - ./java/api_descarga.java:/code/api_descarga.java
    working_dir: /code
    command: ["java", "api_descarga.java"]

  api_email:
    image: openjdk
    volumes:
      - ./java/api_email.java:/code/api_email.java
    working_dir: /code
    command: ["java", "api_email.java"]

  api_wallet:
    image: openjdk
    volumes:
      - ./java/api_wallet.java:/code/api_wallet.java
    working_dir: /code
    command: ["java", "api_wallet.java"]

  qr:
    image: openjdk
    volumes:
      - ./java/qr.java:/code/qr.java
    working_dir: /code
    command: ["java", "qr.java"]

  validacion:
    image: openjdk
    volumes:
      - ./java/validacion.java:/code/validacion.java
    working_dir: /code
    command: ["java", "validacion.java"]
